name: Deploy Project to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Move 3partylicenses.txt to browser folder
        run: mv dist/wedding/3rdpartylicenses.txt dist/wedding/browser/3rdpartylicenses.txt

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CI: true
        run: npm run deploy
